Este fichero de Makfile, que se  usa en sistemas Linux, nos permite cargar en un arduino  un programa sin tener que usar
el IDE  gráfico. La idea  es genial si  utilizamos una  Rapsberry Pi o  Cubieboard conectada a  él, pero que  no tiene
entorno gráfico, y accedemos a esos miniordenadores de forma remota como SSH.
